catalogo/urls.py
from . import views

from django.urls import path

urlpatterns = [
    path('', views.index, name='index'),
    path('libros/', views.VistaDeListaDeLibros.as_view(), name='libros'),
    path('libros/crear/', views.CrearLibro.as_view(), name='libro_crear'),
    path('libros/<int:pk>', views.VistaDeDetallesDeLibros.as_view(), name='detalle_del_libro'),
    path('libros/<int:pk>/actualizar/', views.ActualizarLibro.as_view(), name='libro_actualizar'),
    path('libros/<int:pk>/eliminar/', views.EliminarLibro.as_view(), name='libro_eliminar'),
    path('libros/<uuid:pk>/devolver/', views.devolver_libro, name='devolver_libro'),
    path('libros/<uuid:pk>/renovar/', views.renovar_libro, name='renovar_libro'),
    path('autores/', views.VistaDeListaDeAutores.as_view(), name='autores'),
    path('autores/crear/', views.CrearAutor.as_view(), name='autor_crear'),
    path('autores/<int:pk>', views.VistaDeDetallesDeAutores.as_view(), name='detalle_del_autor'),
    path('autores/<int:pk>/actualizar/', views.ActualizarAutor.as_view(), name='autor_actualizar'),
    path('autores/<int:pk>/eliminar/', views.EliminarAutor.as_view(), name='autor_eliminar'),
    path('mislibros/', views.VistaDeListaDeLibrosPrestados.as_view(), name='misprestamos'),
    path('prestamos/', views.VistaDePrestamosStaff.as_view(), name='todoslosprestamos'),
    path('prestamos/crear/', views.CrearPrestamo.as_view(), name='prestamo_crear'),
]

librerialocal/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalogo/', include('catalogo.urls')),
    path('', RedirectView.as_view(url='catalogo/')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalogo/models.py
from datetime import date, timedelta
import uuid # Requerido para definir instancias unicas por libro

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Genero(models.Model):
    """Modelo que representa un genero de libro"""
    nombre = models.CharField(max_length=200, help_text='Ingresa un género de libro (ejemplo: Ciencia Ficción)')

    def __str__(self):
        return self.nombre


class Lenguaje(models.Model):
    """Modelo que representa un lenguaje"""
    nombre = models.CharField(max_length=200, help_text='Ingresa el Lenguaje natural de un libro (ejemplo: Español)')

    def __str__(self):
        return self.nombre


class Libro(models.Model):
    """Modelo que representa un libro (pero no una copia especifica del libro)"""
    titulo = models.CharField(max_length=200)
    autor = models.ForeignKey('Autor', on_delete=models.SET_NULL, null=True)
    resumen = models.TextField(max_length=1000, help_text='Ingresa una breve descripción del libro')
    isbn = models.CharField('ISBN', max_length=13, help_text='Ingresa el <a href="https://www.isbn-international.org/es/content/¿que-es-un-isbn">número ISBN</a> de 13 carácteres')
    lenguaje = models.ForeignKey('Lenguaje', on_delete=models.SET_NULL, null=True)
    genero = models.ManyToManyField(Genero, help_text='Selecciona un género para este libro')

    
    def desplegar_genero(self):
        """Crea un string para el Genero. Se requiere para desplegar genero en Admin"""
        return ', '.join(genero.nombre for genero in self.genero.all()[:3])
    
    desplegar_genero.short_description = 'Genero'
    
    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('detalle_del_libro', args=[str(self.id)])


class InstanciaDeLibro(models.Model):
    """Modelo que representa una copia especifica de un libro (ejemplo: un libro prestado por la libreria)"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='ID único para este libro en particular en toda la librería')
    libro = models.ForeignKey('Libro', on_delete=models.SET_NULL, null=True) 
    fecha_de_devolucion = models.DateField(null=True, blank=True)
    prestatario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    ESTADO_DEL_PRESTAMO = (
        ('m', 'Mantenimiento'),
        ('p', 'Prestado'),
        ('d', 'Disponible'),
        ('r', 'Reservado'),
    )

    estatus = models.CharField(
        max_length=1,
        choices=ESTADO_DEL_PRESTAMO,
        blank=True,
        default=' ',
        help_text='Disponibilidad del libro',
    )
    
    @property
    def esta_atrasado(self):
        if self.fecha_de_devolucion and date.today() > self.fecha_de_devolucion:
            return True
        return False

    class Meta:
        ordering = ['fecha_de_devolucion']
        permissions = (("can_mark_returned", "Can set book as returned"),)

    def __str__(self):
        return f'{self.libro.titulo} ({self.id})'


class Autor(models.Model):
    """Modelo que representa un autor"""
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    fecha_de_nacimiento = models.DateField(null=True, blank=True)
    fecha_de_deceso = models.DateField('Fallecimiento', null=True, blank=True)

    class Meta:
        ordering = ['apellido', 'nombre']

    def get_absolute_url(self):
        return reverse('detalle_del_autor', args=[str(self.id)])

    def __str__(self):
        return f'{self.apellido}, {self.nombre}'

catalogo/views.py
from datetime import date, timedelta

from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required
from django.forms import ModelForm
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.core.exceptions import ValidationError

from catalogo.models import Libro, Autor, InstanciaDeLibro, Genero, Lenguaje


def index(request):
    """View function para la pagina principal"""
    num_libros = Libro.objects.all().count()
    num_instancias = InstanciaDeLibro.objects.all().count()
    num_autores = Autor.objects.count() # 'all()' esta implicito

    num_instancias_disponibles = InstanciaDeLibro.objects.filter(estatus__exact='d').count()
    
    palabra = 'Harry' # input('Ingresa el título o una palabra del título para ser buscada:')
    num_libros_palabra = list(Libro.objects.filter(titulo__icontains=palabra).values_list('titulo'))

    contexto = {
        'num_libros': num_libros,
        'num_instancias': num_instancias,
        'num_autores': num_autores,
        'num_instancias_disponibles': num_instancias_disponibles,
        'num_libros_palabra': num_libros_palabra,
    }

    return render(request, 'index.html', context=contexto)


class VistaDeListaDeLibros(generic.ListView):
    """View function para todos los libros"""
    model = Libro
    context_object_name = 'lista_de_libros'
    template_name = 'libros/lista_de_libros.html'
    paginate_by = 10


class VistaDeDetallesDeLibros(generic.DetailView):
    """View function para los detalles de un libro"""
    model = Libro
    template_name = 'libros/detalle_del_libro.html'


class VistaDeListaDeAutores(generic.ListView):
    """View function para todos los autores"""
    model = Autor
    context_object_name = 'lista_de_autores'
    template_name = 'autores/lista_de_autores.html'
    paginate_by = 10


class VistaDeDetallesDeAutores(generic.DetailView):
    """View function para los detalles de un autor"""
    model = Autor
    template_name = 'autores/detalle_del_autor.html'


class VistaDeListaDeLibrosPrestados(LoginRequiredMixin, generic.ListView):
    """View function para mis prestamos"""
    model = InstanciaDeLibro
    context_object_name = 'instanciadelibro_lista'
    template_name = 'libros/instanciadelibro_lista_prestados_usuario.html'
    paginate_by = 10
    
    def get_queryset(self):
        return InstanciaDeLibro.objects.filter(prestatario=self.request.user).filter(estatus__exact='p').order_by('fecha_de_devolucion')


class VistaDePrestamosStaff(PermissionRequiredMixin, generic.ListView):
    """View function para todos los prestamos"""
    permission_required = 'catalogo.can_mark_returned'
    model = InstanciaDeLibro
    context_object_name = 'instanciadelibro_lista_staff'
    template_name = 'libros/instanciadelibro_lista_prestados_staff.html'
    paginate_by = 10
    
    def get_queryset(self):
        return InstanciaDeLibro.objects.filter(estatus__exact='p').order_by('fecha_de_devolucion')


class FormDevolverLibro(ModelForm):
    """Form function para devolver un prestamo a la libreria"""

    class Meta:
        model = InstanciaDeLibro
        fields = ['id']


@permission_required('catalogo.can_mark_returned')
def devolver_libro(request, pk):
    instancia_de_libro = get_object_or_404(InstanciaDeLibro, pk=pk)

    if request.method == 'POST':
        form = FormDevolverLibro(request.POST)

        instancia_de_libro.fecha_de_devolucion = date.today() + timedelta(weeks=2)
        instancia_de_libro.estatus = 'm'
        instancia_de_libro.prestatario = None
        instancia_de_libro.save()

        return HttpResponseRedirect(reverse('todoslosprestamos'))

    else:
        form = FormRenovarLibro()

        context = {
          'form': form,
          'instancia_de_libro': instancia_de_libro,
        }

        return render(request, 'libros/devolver_libro.html', context)


class FormRenovarLibro(ModelForm):
    """Form function para aplazar la fecha de devolucion un prestamo"""

    def clean_fecha_de_devolucion(self):
        data = self.cleaned_data['fecha_de_devolucion']

        if data < date.today() + timedelta(days=1):
            raise ValidationError('Fecha inválida - renovación en el pasado')

        if data > date.today() + timedelta(weeks=4):
            raise ValidationError('Fecha inválida - renovación con más de 4 semanas')

        return data

    class Meta:
        model = InstanciaDeLibro
        fields = ['fecha_de_devolucion']
        labels = {'fecha_de_devolucion': 'Fecha de renovacion'}
        help_texts = {'fecha_de_devolucion': 'Mínimo: mañana - Máximo: 4 semanas'} 


@permission_required('catalogo.can_mark_returned')
def renovar_libro(request, pk):
    instancia_de_libro = get_object_or_404(InstanciaDeLibro, pk=pk)
    fecha_de_renovacion_propuesta = date.today() + timedelta(weeks=3)
    form = FormRenovarLibro(initial={'fecha_de_devolucion': fecha_de_renovacion_propuesta})

    if request.method == 'POST':

        form = FormRenovarLibro(request.POST, initial={'fecha_de_devolucion': fecha_de_renovacion_propuesta})

        if form.is_valid():
            instancia_de_libro.fecha_de_devolucion = form.cleaned_data['fecha_de_devolucion']
            instancia_de_libro.save()

            return HttpResponseRedirect(reverse('todoslosprestamos'))

    context = {
      'form': form,
      'instancia_de_libro': instancia_de_libro,
    }

    return render(request, 'libros/renovar_libro.html', context)


class CrearLibro(PermissionRequiredMixin, CreateView):
    """View function para que staff pueda añadir un libro a la base de datos"""
    permission_required = 'catalogo.can_mark_returned'
    model = Libro
    fields = '__all__'
    template_name = 'generic_form.html'


class ActualizarLibro(PermissionRequiredMixin, UpdateView):
    """View function para que staff pueda modificar un libro en la base de datos"""
    permission_required = 'catalogo.can_mark_returned'
    model = Libro
    fields = '__all__'
    template_name = 'generic_form.html'


class EliminarLibro(PermissionRequiredMixin, DeleteView):
    """View function para que staff pueda eliminar un libro a la base de datos"""
    permission_required = 'catalogo.can_mark_returned'
    model = Libro
    success_url = reverse_lazy('libros')
    template_name = 'libros/libro_confirm_delete.html'


class CrearAutor(PermissionRequiredMixin, CreateView):
    """View function para que staff pueda añadir un autor a la base de datos"""
    permission_required = 'catalogo.can_mark_returned'
    model = Autor
    fields = '__all__'
    template_name = 'generic_form.html'


class ActualizarAutor(PermissionRequiredMixin, UpdateView):
    """View function para que staff pueda modificar un autor en la base de datos"""
    permission_required = 'catalogo.can_mark_returned'
    model = Autor
    fields = '__all__'
    template_name = 'generic_form.html'


class EliminarAutor(PermissionRequiredMixin, DeleteView):
    """View function para que staff pueda eliminar un autor a la base de datos"""
    permission_required = 'catalogo.can_mark_returned'
    model = Autor
    success_url = reverse_lazy('autores')
    template_name = 'autores/autor_confirm_delete.html'


class CrearPrestamo(PermissionRequiredMixin, CreateView):
    """View function para que staff pueda añadir una instancia de libro a la base de datos"""
    permission_required = 'catalogo.can_mark_returned'
    model = InstanciaDeLibro
    fields = '__all__'
    template_name = 'generic_form.html'

catalogo/templates/libros/detalle_del_libro.html
{% extends "base_generic.html" %}

{% block sidebar %}
    {{ block.super }}
    {% if perms.catalogo.can_mark_returned %}
      <ul class="sidebar-nav">
        <li><a href="{% url 'libro_actualizar' libro.id %}">Actualizar Libro</a></li>
        <li><a href="{% url 'libro_eliminar' libro.id %}">Eliminar Libro</a></li>
      </ul>
    {% endif %}
{% endblock %}

{% block content %}
    <h1>Título: {{ libro.titulo }}</h1>
    
    <p><strong>Autor:</strong> <a href="{{ libro.autor.get_absolute_url }}">{{ libro.autor }}</a></p>
    <p><strong>Resumen:</strong> {{ libro.resumen }}</p>
    <p><strong>ISBN:</strong> {{ libro.isbn }}</p>
    <p><strong>Lenguaje:</strong> {{ libro.lenguaje }}</p>
    <p><strong>Género:</strong> {{ libro.genero.all|join:", " }}</p>
    
    <div style="margin-left:20px;margin-top:20px">
        <h4>Copias</h4>
        {% for copia in libro.instanciadelibro_set.all %}
            <hr>
            <p style="margin: 0px;" class="{% if copia.estatus == 'd' %}text-success{% elif copia.estatus == 'm' %}text-danger{% else %}text-warning{% endif %}">
                {{ copia.get_estatus_display }}
            </p>
            <p class="text-muted"><strong>Id:</strong> {{ copia.id }}</p>
            {% if copia.estatus != 'd' %}
                <p style="margin-bottom: 0px;" class="{% if copia.esta_atrasado %}text-danger{% endif %}">
                    <strong>Debe ser devuelto:</strong> {{ copia.fecha_de_devolucion }}
                </p>
                {% if perms.catalogo.can_mark_returned %}
                    <a class="btn btn-outline-dark btn-sm" href="{% url 'renovar_libro' copia.id %}">
                        Renovar
                    </a>
                    <a class="btn btn-outline-dark btn-sm" href="{% url 'devolver_libro' copia.id %}">
                        Devolver
                    </a>
                {% endif %}
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

catalogo/templates/libros/devolver_libro.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Devolver: {{ instancia_de_libro.libro.titulo }}</h1>
    <p>Prestatario: {{ instancia_de_libro.prestatario }}</p>
    <p {% if instancia_de_libro.esta_atrasado %}class="text-danger"{% endif %}>Fecha de devolución: {{ instancia_de_libro.fecha_de_devolucion }}</p>

    <p>¿Esta seguro de estar recibiendo el libro cuyo Id es el siguiente?</p>
    <p class="text-muted">{{ instancia_de_libro.id }}</p>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Sí, continuar" />
    </form>
{% endblock %}

catalogo/templates/libros/instanciadelibro_lista_prestados_staff.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Todos los libros prestados</h1>
    {% if instanciadelibro_lista_staff %}
        <ul>
        {% for instancia in instanciadelibro_lista_staff %}
            <li class="{% if instancia.esta_atrasado %}text-danger{% endif %}">
                <a href="{% url 'detalle_del_libro' instancia.libro.pk %}">{{ instancia.libro.titulo }}</a> ({{ instancia.fecha_de_devolucion }}) - {{ instancia.prestatario }}
                <br>
                <p class="text-muted"><strong>Id:</strong> {{ instancia.id }}</p>
            </li>
            <a class="btn btn-outline-dark btn-sm" href="{% url 'renovar_libro' instancia.id %}">
                Renovar
            </a>
            <a class="btn btn-outline-dark btn-sm" href="{% url 'devolver_libro' instancia.id %}">
                Devolver
            </a>
            <hr>
        {% endfor %}
        </ul>
    {% else %}
        <p>No hay libros prestados.</p>
    {% endif %}
{% endblock %}

catalogo/templates/libros/instanciadelibro_lista_prestados_usuario.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Libros prestados</h1>
    {% if instanciadelibro_lista %}
        <ul>
        {% for instancia in instanciadelibro_lista %}
            <li class="{% if instancia.esta_atrasado %}text-danger{% endif %}">
                <a href="{% url 'detalle_del_libro' instancia.libro.pk %}">{{ instancia.libro.titulo }}</a> ({{ instancia.fecha_de_devolucion }})
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No hay libros prestados.</p>
    {% endif %}
{% endblock %}

catalogo/templates/libros/libro_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Eliminar Libro</h1>
    <p>¿Esta seguro de que quiere eliminar al libro: {{ libro }}?</p>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Sí, eliminar" />
    </form>
{% endblock %}

catalogo/templates/libros/lista_de_libros.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Lista de libros</h1>
    {% if lista_de_libros %}
        <ul>
        {% for libro in lista_de_libros %}
            <li>
                <a href="{{ libro.get_absolute_url }}">{{ libro.titulo }}</a> - ({{ libro.autor }})
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No hay libros en la librería.</p>
    {% endif %}
{% endblock %}

catalogo/templates/libros/renovar_libro.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Renovar: {{ instancia_de_libro.libro.titulo }}</h1>
    <p>Prestatario: {{ instancia_de_libro.prestatario }}</p>
    <p {% if instancia_de_libro.esta_atrasado %}class="text-danger"{% endif %}>Fecha de devolución: {{ instancia_de_libro.fecha_de_devolucion }}</p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
           {{ form.as_table }}
        </table>
        <input type="submit" value="Enviar" />
    </form>
{% endblock %}